spring:
  application:
    name: client-service
  h2:
    console:
      settings:
        trace: true

server:
  port: 6060

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user